---
- name: do apt-get update
  apt: 
    update_cache: yes
  
- name: make sure mosquitto are installed
  apt: 
    name: mosquitto 
    state: latest
  
- name: make sure mosquitto is enabled and up and running
  service:
    name: mosquitto
    enabled: yes
    state: started